### PR TITLE
working again

### PR DESCRIPTION
**Pull request by sirber**
Hi,

I got it working again, plus it now fetches pfstools and opencv.
opencv is compiled whitout ffmpeg, opencl and cuda.

Regards,

Stéphane

### CODE REVIEW

**Comment by janLo** [comment]
Thank you! As stretch will be released next year I prefer to not roll back to jessie because of some obscure jpeg lib. But I'll have a look into it as soon as I find time.

Can you cleanup your PR a bit?

* remove commented out code
* keep the changes as small as possible
* there is no point in running apt-get-clean in a separate RUN call, as the packages are already committed to the FS-Layer before

**Comment by sirber** [comment]
Hi, I'm not sure on how I can do that. Do I close this one and create a new one?

**Comment by janLo** [comment]
Try to just push your changes to the branch you created the PR from. Normally this should update the PR.

**Comment by sirber** [comment]
3 years later... closed.

**Pull request closed without merging**
